### ISSUE TITLE
Debugging toolbox to run?

### ISSUE THREAD

**Issue by dahyun-kang** [mboudiaf/RePRI-for-Few-Shot-Segmentation#15]
Hello,

Thank you for open sourcing your project so early! :smiley: 

Could you please share which debugging tool you use for this project or any recommendations?
`pdb` seems not working at hand possibly due to the multiprocessing code base.

**Comment by mboudiaf** [comment]
Hey ! 

Thanks for your interest :D  ! On my side, I usually do not use pdb indeed. I rather debug by putting assert everywhere I can, even for obvious stuff. I admit this is very rudimentary, but actually works quite nicely. One of the reasons I prefer to work with such rudimentary tools (for instance, I save and plot my metrics using numpy and matplotlib instead of more evolved stuff) is that they never let me down ! 

Regardless, if you really want to debug with pdb, I guess you could quite easily turn the code into a traditional single process one. For instance:
https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/5900a52e27621c5772193599cfc85a730a82f327/src/train.py#L328
could simply become `main_worker(0, 1, args)` and then pdb would probably work. I don't currently have access to my hardware to test this, but let me know if that helps for you ! :)

**Comment by dahyun-kang** [comment]
Hello,

Single process run works with `pdb`. Thank you for your prompt and kind reply.
Hope you have a great day :smiley:
