### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by arjvn** [mboudiaf/RePRI-for-Few-Shot-Segmentation#20]
```
RuntimeError: CUDA out of memory. Tried to allocate 528.00 MiB (GPU 0; 11.77 GiB total capacity; 9.33 GiB already allocated; 326.75 MiB free; 9.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Hi Malik, thanks for making your work open source and congrats on CVPR :)

I think I'm facing a similar issue as #12. I've tried changing the batch_size_val to 1 from 200 in config_files/pascal.yaml and in scripts/test.sh but I'm still facing the same error. Im running `bash scripts/train.sh pascal 0 [0] 50` and im using a rtx3060.

**Comment by mboudiaf** [comment]
Hi @arjvn,

Thanks for using the code ! Unfortunately, I think the problem is with the training batch size. Because images are quite large, training with batch size 12 actually requires almost 24 GB if you use a single GPU. Reducing the batch_size_val won't have much impact at that point (you will get the same problem even if you completely comment out the whole validation pipeline). If you want to train with a 12 GB RTX, you should probably use a batch size 5, which may not be ideal considering ResNets use batch normalization layers. Let me know if that helps. I will also update the README to reflect that.

**Comment by arjvn** [comment]
Hi Malik, I've been able to get the training going on a batch size of 5. Thanks for your help. Lets see how it performs on Pascal
